version: '3.8'

services:
  nats:
    image: nats:latest
    command: 
      - "--jetstream"
      - "--store_dir=/data"
      - "--port=4222"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data
    environment:
      - NATS_SERVER_NAME=nats-server

volumes:
  nats-data:
