app:
  name: nats-project
  version: 1.0.0

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 5s
  write_timeout: 5s

nats:
  urls: ["nats://localhost:4222"]
  cluster_id: "test-cluster"
  client_id: "nats-project"
  max_reconnects: 10
  reconnect_wait: 1s
  connect_timeout: 30s
  operation_timeout: 30s

log:
  level: "info"
  format: "json"
  output: "stdout"

metrics:
  enabled: true
  port: 9090
